import pyautogui
from time import sleep
from random import randint


def typeMessageAndEnter(message):
    pyautogui.typewrite(message)
    pyautogui.keyDown('alt')
    pyautogui.keyDown('enter')
    pyautogui.keyUp('enter')
    pyautogui.keyUp('alt')


pyautogui.keyDown('alt')
pyautogui.keyDown('tab')
pyautogui.keyUp('tab')
pyautogui.keyUp('alt')
contact_list = [
]

print("original list: " + str(len(contact_list)))
contact_list_without_chars = []
for contact in contact_list:
    contactNew = contact.replace(" ", "")
    contactNew = contactNew.replace("\(", "")
    contactNew = contactNew.replace("\)", "")
    contact_list_without_chars.append(contactNew)

contact_list_without_duplicates = list(dict.fromkeys(contact_list_without_chars))
print("final list: " + str(len(contact_list_without_duplicates)))
for contact_element in contact_list_without_duplicates:
    sleep(randint(1, 2))
    # pyautogui.click(100, 110) bigminotor
    #pyautogui.click(322, 225)  # small monitor real whatsapp
    pyautogui.click(258, 580)  # small monitor web whatsapp with disconnected phone
    #pyautogui.click(250,370) # small monitor web whatsapp
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('a')
    pyautogui.keyUp('ctrl')
    pyautogui.keyUp('v')
    pyautogui.hotkey('delete')

    sleep(randint(1, 2))
    pyautogui.typewrite(contact_element)
    sleep(randint(1, 2))
    pyautogui.hotkey('enter')
    sleep(randint(1, 2))
    # pyautogui.click(698, 1011)
    # sleep(randint(1, 2))
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('v')
    pyautogui.keyUp('ctrl')
    pyautogui.keyUp('v')
    sleep(randint(1, 2))
    # typeMessageAndEnter("🌸 *Refresh Your Happiness* with *Bharat Vig Ji*")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("You are invited for a Lively Interactive knowledge and open Q & A Session with Senior International Faculty ✨ *Bharat Vig Ji* ✨")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("Resolve your doubts, learn to *practically apply* knowledge to your life!")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("📆  *Tuesday 26th Jan*")
    # typeMessageAndEnter("🕰️  *7pm - 8pm*")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("_Click below to get a zoom link for session:_")
    # typeMessageAndEnter("http://tiny.cc/refreshhappiness")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("*Open for All*")
    # typeMessageAndEnter("(c) 9810057557")
    # typeMessageAndEnter("http://tiny.cc/secretoflife")
    # typeMessageAndEnter("(c) 9810057557 | 7738086079")
    #typeMessageAndEnter("*Meditation* unlocks all success in life!")
    #typeMessageAndEnter("Learn the art of *Joyful Living!*")
    #typeMessageAndEnter("*Today (Sunday)* 11th April 12pm - soak yourself in meditation - experience live!")
    #typeMessageAndEnter("Register here to get a zoom link: http://tiny.cc/joyfulliving")
    #typeMessageAndEnter("Please do forward to friends and family who are interested in learning about meditation")
    # typeMessageAndEnter("Register for the *FREE* session by clicking on http://tiny.cc/managemytime. Session is facilitated by *Bharat Vig* ji, who is an Art of Living teacher for more than 2 decades!")
    # typeMessageAndEnter("Please do forward to friends and family who are interested in learning about the wonderful skill of time management!")
    typeMessageAndEnter("On the beautiful occasion of *Chaitra Navratri*✨ attend the *Online* Sahaj Samadhi program!!")
    typeMessageAndEnter("")
    typeMessageAndEnter("Two batches on 16 Apr (7am to 9am, 7pm to 9pm)")
    typeMessageAndEnter("Combined batch on 17, 18 Apr (7pm to 9pm)")
    typeMessageAndEnter("")
    typeMessageAndEnter("For 16 morning register http://aolt.in/538209")
    typeMessageAndEnter("For 16 evening register http://aolt.in/540725")
    typeMessageAndEnter("")
    typeMessageAndEnter("*HURRY* ONLY 10 seats per batch!")
    typeMessageAndEnter("About *Bharat Vig ji* Been with Gurudev since age of 13 and also His secretary for 7 years, taking Sahaj, VTP, TTP, Happiness, DSN and numerous courses, session are going to be *full of learning*")
    typeMessageAndEnter("")
    typeMessageAndEnter("Do forward to friends and family who have not done Sahaj. Message me if you are interested in repeating as well")
    # typeMessageAndEnter("*Meditation* unlocks all success in life!")
    # typeMessageAndEnter("Jai Gurudev! Bharat Vig Ji is an entrepreneur, AOL teacher for 20+ years, teaches VTP, TTP, Sahaj and numerous courses and has been Gurudev's secretary for over 7 years!")
    # typeMessageAndEnter("Join him to learn about time management this Sunday 20 Dec by clicking on http://tiny.cc/managemytime. Please do forward to friends and family who are interested in learning about the wonderful skill of time management!")
    # typeMessageAndEnter("We wish to achieve so much in life, but time, days, years are just slipping away! ")
    # typeMessageAndEnter("Isn't it? ")
    # typeMessageAndEnter("Wouldn't it be nice if we knew how to accomplish more in a given timespan....")
    # typeMessageAndEnter("Learn the life-hacks, tips & easy to adopt techniques in this Free Masterclass with none other than *Bharat Vig* ji!")
    # typeMessageAndEnter("Today (Sunday) *1pm to 2pm*")
    # typeMessageAndEnter("Register here : http://tiny.cc/managemytime and also forward to friends and family (specially students) who want to learn time management!")
    # typeMessageAndEnter("This Holi - take sankalpa to deepen your sadhana, take a big step towards meditation !!")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("https://youtu.be/O20yQvzK7gg")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("Now do Sahaj Samadhi with *Bharat Vig ji*, who has been personal secretary to Gurudev for 7+ years and been taking Sahaj courses for over 20 years!")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("Register *NOW*")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("Dates: *Mar 26 to 28*")
    # typeMessageAndEnter("Evening 7pm to 9pm")
    # typeMessageAndEnter("http://aolt.in/538209")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("Contact: 9810057557 for any questions!")
    # typeMessageAndEnter("")
    # typeMessageAndEnter("Spread the word - please share this message with as many as you can !!")
    pyautogui.hotkey("enter")
